api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
    html: ["text/html"]
    jsonhal: ["application/hal+json"]
    csv: ["text/csv"]
